# Site settings
title: Matthew Hirt | Missiologist
description: "The personal website of Matthew Hirt"
url: "http://www.jacoporabolini.com/emerald"
author:
  name: "Matthew Hirt"
  email: "mhirt@sebts.edu"
  url: "matthewhirt.gq"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: 
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
"The personal website of Matthew Hirt"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
